version: "3.8"

services:
  db-mysql:
    image: mysql:5.7.40
    container_name: mysql-laptopshop
    restart: always
    environment:
      MYSQL_DATABASE: laptopshop
      MYSQL_ROOT_PASSWORD: 172606
    ports:
      - "3307:3306"
    expose:
      - "3306"

  app:
    container_name: spring-mvc-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/laptopshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 172606
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db-mysql
